# Generated by Django 5.2.5 on 2025-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(max_length=10),
        ),
    ]
