# Generated by Django 5.2.5 on 2025-09-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_pricehistory_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricehistory",
            name="asset",
        ),
    ]
