# Generated by Django 5.2.5 on 2025-09-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.asset",
            ),
        ),
    ]
