# Generated by Django 5.2.5 on 2025-09-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_transaction_asset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="asset",
        ),
    ]
