# Generated by Django 5.2.5 on 2025-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="money",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
